repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
- hooks:
  - id: black
  repo: https://github.com/psf/black
  rev: 22.12.0
- hooks:
  - args:
    - --profile
    - black
    id: isort
  repo: https://github.com/pycqa/isort
  rev: 5.12.0
- hooks:
  - exclude: tests/
    id: mypy
  repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991
- hooks:
  - id: poetry-check
  repo: https://github.com/python-poetry/poetry
  rev: 1.3.0
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.40.0
