name: Test environment

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install caching
        uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.3
      - name: Install dependencies
        run: poetry install --without docs,dev
      - name: Run tests
        run: poetry run pytest ./tests/test_executors/
